// <auto-generated />
namespace Authentication_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fghfj : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fghfj));
        
        string IMigrationMetadata.Id
        {
            get { return "202304180552222_fghfj"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
